### ISSUE TITLE
Investigate extended RFI excision for some frequencies

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#594] opened 2019-11-08 21:36 UTC
We are seeing every now and again that the RFI system will start to excise some frequencies at a constant rate for an extended period of time. These may be as long as 12 hours. The frequencies seem to differ between occurrences of the event, and may occasionally coincide at the start with an actual high RFI rate (but not always).

**Comment by mondana** [comment] 2019-11-08 21:39
<img width="906" alt="data_loss_ 2019-11-07 at 7 12 26 PM" src="https://user-images.githubusercontent.com/1731211/68512398-2376e600-022d-11ea-82ad-26a76017ca3b.png">

**Comment by james-s-willis** [comment] 2019-11-11 21:00
After speaking to Jacob this morning he thinks that the extended RFI excision is down to lost packets coming from the FPGA, due to the regular patterns in the above plot. His RFI kernels are independent of frequency so shouldn't be regularly excising the same frequency. 

To investigate, I plotted the number of nodes above a given load and above 100 packet loss:

![Node load and packet loss](https://user-images.githubusercontent.com/36906682/68620544-ad2beb00-049b-11ea-9abb-31c4455fe20d.png)

There doesn't seem to be a correlation with the 5th and 6th Nov events. However, there was a large event on the 8th Nov at 16:00 ET. I'm not sure if this is related to the extended RFI excision problem but could I get a waterfall plot like the one above for this time period? @mondana? Who produced one the above?

**Comment by andrerenard** [comment] 2019-11-11 21:13
Just to add to this, from what I can see, the pattern in the waterfall plot doesn't look like it could be produced by packet loss.  I'd expected to see a pattern with a regular 100MHz repeat, but there are features that don't show up every 100MHz.

**Comment by mondana** [comment] 2019-11-12 05:23
@saurabh-astro did, we can ask him. He does not seem to be in kotekan group here.

**Comment by jrs65** [comment] 2019-11-12 06:43
I agree with @andrerenard here. As he says, we don't see any 100 MHz repeating in the above plots, but also the plot that Saurabh generated is specifically the RFI excised fraction, and does not include any packet losses. As the only thing that touches that is the RFI system, that is at least the proximate cause of what we're seeing, if not the ultimate cause.

**Comment by james-s-willis** [comment] 2019-11-12 16:43
Me and @andrerenard have been talking about this issue and we know what the problem is now. If we get two bad input lists from coco in quick succession (<0.5s) it's possible that kotekan can drop the 2nd update. I am going to create a fix for this by buffering the bad input list so that none are dropped.

**Comment by saurabh-astro** [comment] 2019-11-12 18:00
![Screen Shot 2019-11-12 at 1 00 31 PM](https://user-images.githubusercontent.com/19757655/68697257-74981a00-054c-11ea-8102-304bb4b65a8a.png)
![Screen Shot 2019-11-12 at 1 00 37 PM](https://user-images.githubusercontent.com/19757655/68697258-74981a00-054c-11ea-98ce-15506d6d400b.png)

**Comment by jrs65** [comment] 2019-11-12 18:11
@andrerenard @james-s-willis does that correlate with the actual set of flagging updates that were sent to the GPU nodes. It would have to start with a double update within 0.5s (@ssiegelx, can that even happen?), and then have *no more* updates for the next twelve hours as that would presumably reset things.

**Comment by jrs65** [comment] 2019-11-12 18:17
<img width="1557" alt="image" src="https://user-images.githubusercontent.com/695206/68698310-84f0ca80-0535-11ea-998e-19d7f00b16e2.png">
It's not implausible. Here's a similar time range to Saurabh's first plots. There are a few long time periods with no updates, and then in the run up to them there look to be updates happening frequently.

**Comment by jrs65** [comment] 2019-11-12 18:20
Certainly that last saw tooth (6th Nov 16:30 - 7th 10am) seems to match up with the last extended period in Saurabh's plot, but the period immediately beforehand that one in Saurabh's plot does not have a correspondence with a single interval in the flagging update plot.

**Comment by ssiegelx** [comment] 2019-11-12 19:33
It's not possible for the flagging broker to generate two updates in less than 3 seconds of each other (this is a configurable parameter).

![Screen Shot 2019-11-12 at 2 25 56 PM](https://user-images.githubusercontent.com/7007082/68703324-69e38200-0558-11ea-8148-b38f334b5993.png)

Here is the fraction of data masked and the number of inputs considered bad by the RFI test as recorded by the flagging broker.  There does not appear to be a change in the number of bad inputs coincident with the events (at least not for the second event).

**Comment by james-s-willis** [comment] 2019-11-12 20:20
I have looked in the logs to show that we can get two bad input lists in quick succession:

```
Oct 28 20:05:24 cn3g2 kotekan[21171]: /gpu/gpu_0/commands/11: Got new bad inputs list before applying the last list, not applying new bad inputs!
Oct 28 20:05:24 cn3g2 kotekan[21171]: /gpu/gpu_1/commands/11: Got new bad inputs list before applying the last list, not applying new bad inputs!
Oct 28 20:05:24 cn3g2 kotekan[21171]: /gpu/gpu_2/commands/11: Got new bad inputs list before applying the last list, not applying new bad inputs!
Oct 28 20:05:24 cn3g2 kotekan[21171]: /gpu/gpu_3/commands/11: Got new bad inputs list before applying the last list, not applying new bad inputs!
```

although looking at multiple nodes I could not find the same message around the 5th and 6th Nov events. So this problem still needs fixing in kotekan but it may or may not be the solution to the extended RFI excision.

Is it possible that there is a marginally performing feed? And is there a way that we could test this?

**Comment by jrs65** [comment] 2019-11-12 20:21
@james-s-willis Isn't that just each GPU getting the same update?

**Comment by jrs65** [comment] 2019-11-12 20:22
@james-s-willis sorry, the full message is cut off, I see it now.

**Comment by jrs65** [comment] 2019-11-12 20:23
That could happen if the messages get bunched up in `coco` I guess.

**Comment by andrerenard** [comment] 2019-11-12 20:28
@jrs65 yeah I also think this is a problem of the messages getting bunched up in `coco`.   However while this does look like a problem, and one that @james-s-willis is now working on, I also agree that it doesn't seem to correlate to the original problem we are seeing.  

Is it possible that one feed is going bad in those time period, but it's "bad enough" by some metric to get flagged in the bad input mask?   Is there a way to plot the statistics of the all the unmasked feeds for the same period to see if one stands out?   (I think it does look like a digital problem, and we'll keep looking for that, but it might be worth probing the analog side a little more as well.)

**Comment by andrerenard** [comment] 2019-11-12 20:41
Two other questions I have: 
1) Is there any time variability in the amount of FRI zeroed in comb pattern?  And does it vary from "tooth" to "tooth" amount in the comb parts.   If that makes sense? 
2) What does a waterfall plot of the autocorrelations look like from this time period? 
What I'm trying to answer with the questions above is could this be some kind of "metadata" bug, where we are always setting a fixed amount of sample loss, without actually losing any samples.

**Closed** 2019-11-19 17:04 UTC
